### ISSUE TITLE
Implement Mongo database backups

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#137]
A pod will take care of backups when run in production mode

**Comment by lrebscher** [comment]
* Different ways to do a MongoDB Backups: https://docs.mongodb.com/manual/core/backups/
* [mongodump](ohttps://docs.mongodb.com/database-tools/mongodump/) is a popular choice, but not suited for sharded clusters:
> mongodump and mongorestore cannot be part of a backup strategy for 4.2+ sharded clusters that have sharded transactions in progress, as backups created with mongodump do not maintain the atomicity guarantees of transactions across shards. [source](https://docs.mongodb.com/manual/core/backups/)
* Since we're not any time near needing a sharded mongodb cluster, it should be fine to start with mongodump

* Volume Snapshots as DB agnostic method, but couldn't find good way to schedule these. Rather useful for a manual backup: https://kubernetes.io/docs/concepts/storage/volume-snapshots/
