### ISSUE TITLE
Cleanup of workflows volumes

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#152]
Workflow volumes are often used to temporary store output. Need to set up some cleaning strategy.

Also add an optional pod cleanup (GC) strategy.

**Comment by lrebscher** [comment]
**Good to know:**

* If a Volume is bound to a Workflow, it should be bound to the lifecycle of a workflow and destroyed once the workflow ends. https://argoproj.github.io/argo-workflows/examples/#volumes

**Comment by zsinnema** [comment]
@lrebscher imho the volume should be deleted at workflow job deletion
in the past I've implemented 'TTLSecondsAfterFinished' for the workflow job (default 24x60x60 seconds). This should cleanup the task/job and also the (volumeClaimTemplates) volumes

**Comment by lrebscher** [comment]
@zsinnema
* are you referring with a "workflow job" to a template step in a workflow or the workflow itself? Just getting started with Argo, so want to be sure we're talking about the same thing :)
* Okay, more precisely: based on what I can see in the docs, you can define volumes as well on the template level, in this case it's bound to the lifecycle of the template step in a workflow. If you share data across template steps in a workflow, you can define the volume at workflow level. The answer to when it should be deleted depends on what you want to do with the volume. And of course there is a another case where you want to use an existing persistent volume across and just define a claim, but that's sth I want to discuss next week.
* TTL strategy as shown in this [example](https://github.com/argoproj/argo-workflows/blob/master/examples/gc-ttl.yaml)?  Or a custom implementation? You said you already implemented it: in this project? If yes, is it still implemented? If not, why not? Maybe we can have a quick call Monday and you can bring me on the same page, what do you say?

**Comment by zsinnema** [comment]
@lrebscher workflow (job/task) are all the same for me, I'm refering to an instance not a "class"/"template"

you can see here https://github.com/MetaCell/cloud-harness/blob/28b217d5bdb0295b48e3d2b884c3f3bcc50a11b5/libraries/cloudharness-common/cloudharness/workflows/operations.py#L73 what I've implemented

**Comment by lrebscher** [comment]
Okay, when I'm talking here about a lifecycle of a workflow, I mean a concrete workflow instance, not the resource definition. The TTLSecondsAfterFinished is currently placed at the workflow level. A workflow can consist of multiple tasks/jobs/steps, if you say "workflow task/job" I think of one of the tasks inside a workflow, not the workflow itself but you seem to mean a particular workflow instance, for me that's not the same since a volume could be bound to a workflow or a task inside a workflow

I suggest to have a quick chat @zsinnema @filippomc next week to talk an approach for the cleanup strategy through. Need to know more about your opinions, the requirements, if the automatic volume cleanup that Argo claims to perform for certain kind of volumes might not be sufficient for these volumes.

E.g. I'm confused by the following: a Volume that is only used as tmp storage in one workflow instance and is created as in the example that I listed above: https://argoproj.github.io/argo-workflows/examples/#volumes , is claimed by Argo to be deleted automatically once the workflow completes. @zsinnema  when you say you want a volume to be deleted on deletion of a workflow (instance), that volume should have already been deleted by Argo in this case, or am I seeing this wrong?

**Comment by filippomc** [comment]
So many words, let me try to summarize (and please correct me if I'm wrong).

1. We want to set up a cleanup strategy for volumes and pods
2. @zsinnema suggests that TTLSecondsAfterFinished should remove both terminated pod and related resources, volume included
3. Not really clear at the moment the outcome of this for single tasks and volumes.

I propose to make a test around this with a fast TTL and see what happens to all resources.

**Comment by lrebscher** [comment]
I just tested an example using Argo's offered `ttlStrategy` and `podGC` and can confirm that Argo's automatic cleanup of volumes (those defined inside the workflow) and cleanup of Pods works fine.

Thus, it would make sense to use `ttlStrategy` that Argo intends users to use over `TTLSecondsAfterFinished` to ensure that Argo can perform its cleanup properly.
@zsinnema what do you think?

**Comment by zsinnema** [comment]
@lrebscher lgtm
