### ISSUE TITLE
Implement Postgres database backups

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#157]
Use or take inspiration from image https://github.com/prodrigestivill/docker-postgres-backup-local

**Comment by lrebscher** [comment]
For the remaining DBs we could use Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

* Here is an example for MongoDB: https://www.cloudytuts.com/tutorials/kubernetes/how-to-backup-and-restore-mongodb-deployment-on-kubernetes/

**Comment by filippomc** [comment]
Cronjob seems a very nice solution, if can find a solution that implements smart retention would be great

**Comment by lrebscher** [comment]
> Cronjob seems a very nice solution, if can find a solution that implements smart retention would be great
 
[rotate-backups](https://github.com/xolox/python-rotate-backups) comes pretty close to this, besides that I couldn't really find anything useful. 

With or without rotate-backups we could approach it as follows:

1. Create DB dump
  * Run a kubernetes CronJob
  * It uses the DB specific CLI tool to create a dump and tar it
  * the dump is stored with timestamp as name on a different storage
  
2.  Cleanup Backup storage
  * Run another CronJob or continue in the previous one
  * Either use basic unix commands to delete all files older than X days if we have more than Y files or use `rotate-backups` to allow for more complex rotation

In order to use rotate-backups we have to prepare a Python image, install the rotate-backups package and configure an init file (see [usage](https://rotate-backups.readthedocs.io/en/latest/readme.html#usage)). Maybe too much effort when a simple retention policy would be sufficient.

@filippomc what do you think?

**Comment by lrebscher** [comment]
Also see my comment in #137
