### ISSUE TITLE
Refactor keycloak user/password use to connect to keycloak from CH auth module

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#222]
since we now don't have the username and password as an attribute in values.yaml of accounts anymore we need to refactor the use here: 
https://github.com/MetaCell/cloud-harness/blob/43bc7359588991a16ddaab78bb561ef42c65f62f/libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py#L20

and here:
https://github.com/MetaCell/cloud-harness/blob/43bc7359588991a16ddaab78bb561ef42c65f62f/libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py#L90

**Comment by lrebscher** [comment]
### AdminClient with client-id/secret

Using a newly created client in the ch realm (by modifying the realm.json), I receive a 403 on methods such as `get_users` or `get_clients`, seems that I have insufficient permissions. But there are no client roles available that I can set in the ch realm.

Since we use the AdminClient, we likely need a client with admin role -> only possible if client belongs to the master realm (?).

**Options**

* Figure out whether it's possiblet to assign a client the admin role when the client belongs to the ch realm
* Configure a client with admin role in the master realm

  * By importing multiple realms (as realm.json): https://stackoverflow.com/questions/61184888/how-to-import-multiple-realm-in-keycloak 
  * using [admin-cli tool](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/admin-cli.html) and add a custom start script (provided by Docker image) - can import the configured client via json file -> good to have if we want to configure more stuff on startup or run checks
* Assign the admin user a client-id and client-secret

  * How? We have the same options as for new client in master realm: Can import a modified realm.json or use the admin-cli tool
  * Or, can we do this by setting env variables  similar to setting admin pw and user? But, doesn't seem to be possible, couldn't find anything in the docs

**Comment by filippomc** [comment]
This looks like the same of #361 @zsinnema
