### ISSUE TITLE
Micro service / application dependency manager

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#72]
For applications / micro services which depend on other apps/services we need to have a management service/system in place.

This card is for create/starting/ a discussion thread of thoughts and ideas

Deployment dependency management:
* when can a service start (depends on, wait for)
* when can a service stop (depends on, wait for)

Operational dependency management:
* what needs to be done with depending services in case a service is down (cascade dependency)

....

**Comment by filippomc** [comment]
It turns out that using liveness and readiness probes to deal with dependencies may not be a good idea (as the above article suggests): there is not much to gain in blocking all application pods when a hard requirement is not met. The application should be able to deal with dependency errors in a way that allows the user to see that the system is temporarily down and retry if needed.
